#!/usr/bin/env python3
"""Checked reproduction runner for the paper's computational metrics.

Runs the re-identification harnesses at the shipped configuration and compares what YOU measured
against what the paper reports (reproduce/expected_results.json), within stated tolerances. It
does not invent numbers: targets that need hardware or data you do not have are reported as
BLOCKED with exactly what is missing, and the hardware-bound targets (visual utility, system
cost) are guided-manual by design.

  python reproduce/reproduce.py --list
  python reproduce/reproduce.py --run checkout
  python reproduce/reproduce.py --run gait-class3
  python reproduce/reproduce.py --run gait-class4            # ~9 GPU-hours: 3 arms x 3 seeds
  python reproduce/reproduce.py --run gait-class4 --skip-train   # score existing checkpoints only
  python reproduce/reproduce.py --run appearance-class12 --dataset-root <reid_dataset_flat>
  python reproduce/reproduce.py --check gait-class3          # compare an existing output only

Every run appends to reproduce/REPRODUCTION_REPORT.md, so the report accumulates one section per
target as you work through them. The human-readable mirror of every command and requirement is
reproduce/config.yaml.
"""
import argparse
import datetime
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EXPECTED = json.load(open(os.path.join(HERE, "expected_results.json"), encoding="utf-8"))
REPORT = os.path.join(HERE, "REPRODUCTION_REPORT.md")

GAIT = os.path.join(ROOT, "evaluation", "privacy", "gait")
APP = os.path.join(ROOT, "evaluation", "privacy", "appearance")
REID_REPORTS = os.path.join(ROOT, "evaluation", "privacy", "reports", "reid")


# ---------------------------------------------------------------- helpers

def run(cmd, cwd):
    print(f"\n$ {' '.join(cmd)}   (cwd: {os.path.relpath(cwd, ROOT)})", flush=True)
    return subprocess.run(cmd, cwd=cwd).returncode


def need(paths):
    """Return the subset of prerequisite paths that are missing."""
    return [p for p in paths if not os.path.exists(p)]


def compare(rows, measured, expected_block, arm_key_map, metric_keys):
    """rows += one entry per (arm, metric): expected vs measured vs verdict."""
    ok = True
    for harness_arm, exp_arm in arm_key_map.items():
        exp = expected_block["arms"][exp_arm]
        got = measured.get(harness_arm)
        for mk_meas, mk_exp in metric_keys:
            e = exp[mk_exp]
            if got is None or mk_meas not in got:
                rows.append((exp["paper_name"], mk_exp, e["value"], e["tol"], None, "MISSING"))
                ok = False
                continue
            v = float(got[mk_meas])
            hit = abs(v - e["value"]) <= e["tol"]
            rows.append((exp["paper_name"], mk_exp, e["value"], e["tol"], round(v, 2),
                         "PASS" if hit else "OUT OF TOLERANCE"))
            ok = ok and hit
    return ok


def emit(target, rows, ok, notes=""):
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [f"\n## {target}  ({stamp})  ->  {'PASS' if ok else 'CHECK'}\n"]
    if rows:
        lines.append("| Arm | Metric | Paper | Tol | Measured | Verdict |")
        lines.append("|---|---|---|---|---|---|")
        for arm, met, e, t, v, verdict in rows:
            lines.append(f"| {arm} | {met} | {e} | ±{t} | {v if v is not None else 'n/a'} | {verdict} |")
    if notes:
        lines.append("\n" + notes)
    block = "\n".join(lines) + "\n"
    print(block)
    new = not os.path.exists(REPORT)
    with open(REPORT, "a", encoding="utf-8") as f:
        if new:
            f.write("# Reproduction report\n\nGenerated by `reproduce/reproduce.py`. One section "
                    "per target per run; newest at the bottom. 'PASS' means every compared value "
                    "landed within the stated tolerance of the paper's number; 'CHECK' means at "
                    "least one did not (or was missing) and deserves a look at the protocol, the "
                    "data setup, or the configuration before any conclusion is drawn.\n")
        f.write(block)
    return ok


# ---------------------------------------------------------------- targets

def t_checkout(_a):
    cmds = [
        [sys.executable, "tier1/tests/test_gait_anon.py"],
        [sys.executable, "tier1/tests/test_gait_mask_anon.py"],
        [sys.executable, "tier1/src/edge_runner_pi5/test_config_contract.py"],
        [sys.executable, "tier2_cloud/src/comfyui_custom_nodes/test_egress_guard.py"],
        # Config parity + golden vectors: the shipped constants are the ones the tables name, and
        # both shipped defences still emit byte-identical output on fixed synthetic input. A
        # provenance check proves the BYTES did not move; this proves the BEHAVIOUR did not.
        [sys.executable, "tier1/tests/test_shipped_parity.py"],
    ]
    fails = [c[-1] for c in cmds if run(c, ROOT) != 0]
    return emit("checkout (static verification, incl. vendored-byte provenance)", [], not fails,
                "All five suites passed." if not fails else
                "FAILED: " + ", ".join(fails) + ". A provenance failure means the defence bytes "
                "in this checkout are not the ones the published numbers were measured on.")


def check_class3(_a):
    out = os.path.join(REID_REPORTS, "CLASS3.json")
    if not os.path.exists(out):
        return emit("gait-class3", [], False, f"No output at {out}. Run the target first.")
    res = json.load(open(out))["results"]
    exp = EXPECTED["gait_reid"]["class3_unlearned"]
    rows = []
    ok = compare(rows, res, exp,
                 {"RAW-control": "RAW-control", "qsize_m10_smooth": "qsize_m10_smooth", "e2": "e2"},
                 [("top1", "rank1"), ("top5", "rank5")])
    return emit("gait-class3 (unlearned gait adversary, CASIA-B)", rows, ok,
                "Chance floors are measured per run; the paper's pooled floors are "
                f"{exp['chance_rank1']['value']} / {exp['chance_rank5']['value']} (rank-1/5).")


def t_class3(a):
    missing = need([os.path.join(GAIT, "data", "casia-b_pose_test.csv"),
                    os.path.join(GAIT, "data", "casia-b_pose_train_valid.csv")])
    if missing:
        return emit("gait-class3", [], False,
                    "BLOCKED, missing:\n" + "\n".join("* " + m for m in missing) +
                    "\n\nSetup commands: docs/reproduction.md, 'Dataset setup'.")
    os.makedirs(REID_REPORTS, exist_ok=True)
    rc = run([sys.executable, "untrained_reid.py",
              "--configs", "RAW-control,qsize_m10_smooth,e2",
              "--out", os.path.join(REID_REPORTS, "CLASS3.json")], GAIT)
    if rc != 0:
        return emit("gait-class3", [], False, f"harness exited {rc}")
    return check_class3(a)


def check_class4(_a):
    out = os.path.join(REID_REPORTS, "CLASS4.json")
    if not os.path.exists(out):
        return emit("gait-class4", [], False, f"No output at {out}. Run the target first.")
    res = {k: v["mean"] for k, v in json.load(open(out))["results"].items()}
    exp = EXPECTED["gait_reid"]["class4_adaptive"]
    rows = []
    ok = compare(rows, res, exp,
                 {"RAW-control": "RAW-control", "qsize_m10_smooth": "qsize_m10_smooth", "e2": "e2"},
                 [("top1", "rank1"), ("top5", "rank5")])
    return emit("gait-class4 (adaptive adversary, retrained on protected output)", rows, ok,
                "Retraining is stochastic: tolerances include the published seed spread. Compare "
                "means over the same number of seeds, never a single seed against a mean.")


def t_class4(a):
    missing = need([os.path.join(GAIT, "data", "casia-b_pose_test.csv"),
                    os.path.join(GAIT, "vendor", "GaitGraph", "src")])
    if missing:
        return emit("gait-class4", [], False,
                    "BLOCKED, missing:\n" + "\n".join("* " + m for m in missing))
    if not a.skip_train:
        for cfg in ("RAW-control", "qsize_m10_smooth", "e2"):
            rc = run([sys.executable, "tm3_retrain.py", "--config", cfg,
                      "--epochs", "100", "--seeds", "0,1,2", "--tag", "repro"], GAIT)
            if rc != 0:
                return emit("gait-class4", [], False, f"retraining {cfg} exited {rc}")
    rc = run([sys.executable, "score_class4.py",
              "--configs", "RAW-control,qsize_m10_smooth,e2",
              "--tag", "repro", "--seeds", "0,1,2",
              "--out", os.path.join(REID_REPORTS, "CLASS4.json")], GAIT)
    if rc != 0:
        return emit("gait-class4", [], False,
                    f"scorer exited {rc} (a non-zero exit includes self-gate failures; "
                    "read its output)")
    return check_class4(a)


def check_class12(_a):
    out = os.path.join(APP, "reports", "CLASS12.json")
    if not os.path.exists(out):
        return emit("appearance-class12", [], False, f"No output at {out}. Run the target first.")
    d = json.load(open(out))
    rows, ok = [], True
    for cls, expkey in (("class1", "class1_gei_nn"), ("class2", "class2_frozen_gaitbase")):
        if cls not in d:
            continue
        exp = EXPECTED["appearance_reid"][expkey]
        ok &= compare(rows, d[cls]["arms"], exp,
                      {"raw": "raw", "mirage": "mirage", "dp2": "dp2"},
                      [("rank1", "rank1"), ("rank5", "rank5")])
        n = d[cls].get("null_rank1")
        if n is not None:
            e = exp["chance_rank1"]
            hit = abs(n - e["value"]) <= e["tol"]
            rows.append((f"(measured null, {cls})", "chance_rank1", e["value"], e["tol"],
                         round(n, 2), "PASS" if hit else "OUT OF TOLERANCE"))
            ok &= hit
    return emit("appearance-class12 (GEI + frozen GaitBase on the capture corpus)", rows, ok)


def t_class12(a):
    if not a.dataset_root:
        return emit("appearance-class12", [], False,
                    "BLOCKED: pass --dataset-root <reid_dataset_flat>. The evaluation dataset "
                    "shows real people and is distributed separately from this code repository.")
    missing = need([a.dataset_root,
                    os.path.join(a.dataset_root, "FLAT_MANIFEST.csv"),
                    os.path.join(ROOT, "evaluation", "privacy", "silhouette", "data", "CASIA-B",
                                 "Baseline", "GaitBase_DA", "checkpoints", "GaitBase_DA-60000.pt")])
    if missing:
        return emit("appearance-class12", [], False,
                    "BLOCKED, missing:\n" + "\n".join("* " + m for m in missing))
    steps = [
        [sys.executable, "make_corpus_manifest.py", "--dataset-root", a.dataset_root],
        [sys.executable, "extract_arm.py", "--arm", "raw", "--dataset-root", a.dataset_root,
         "--video-dir", os.path.join(APP, "corpus_10fps"), "--also-mirage"],
    ]
    if os.path.isdir(os.path.join(APP, "baselines_dp2", "out")):
        steps.append([sys.executable, "extract_arm.py", "--arm", "dp2",
                      "--dataset-root", a.dataset_root,
                      "--video-dir", os.path.join(APP, "baselines_dp2", "out"), "--no-pose"])
        arms = "raw,mirage,dp2"
    else:
        print("\n[note] baselines_dp2/out not found: scoring raw + mirage without the "
              "DeepPrivacy2 baseline. See baselines_dp2/run_dp2.sh to add it.")
        arms = "raw,mirage"
    steps.append([sys.executable, "class12_silhouette.py", "--arms", arms, "--reps", "40"])
    for cmd in steps:
        rc = run(cmd, APP)
        if rc != 0:
            return emit("appearance-class12", [], False, f"step exited {rc}: {' '.join(cmd[:3])}")
    return check_class12(a)


def t_manual(name):
    def f(_a):
        block = EXPECTED.get("visual_utility" if "utility" in name else "system_cost", {})
        return emit(name, [], True,
                    "Guided-manual target: it needs the capture corpus and re-rendered outputs "
                    "(visual utility) or the physical hardware rig (system cost), so this runner "
                    "does not execute it. Commands and requirements: reproduce/config.yaml. "
                    "Reference values for comparison:\n\n```json\n"
                    + json.dumps(block.get("reference_values", {}), indent=2) + "\n```")
    return f


TARGETS = {
    "checkout": (t_checkout, "static tests + vendored-byte provenance (no data needed)"),
    "gait-class3": (t_class3, "unlearned gait adversary on CASIA-B (needs the CSVs)"),
    "gait-class4": (t_class4, "adaptive adversary, retrains 3 arms x 3 seeds (needs CUDA; hours)"),
    "appearance-class12": (t_class12, "GEI + frozen GaitBase on the capture corpus (needs the dataset)"),
    "visual-utility": (t_manual("visual-utility"), "guided-manual: matched-seed re-renders needed"),
    "system-cost": (t_manual("system-cost"), "guided-manual: Pi 5 / S25 Ultra hardware needed"),
}
CHECKS = {"gait-class3": check_class3, "gait-class4": check_class4,
          "appearance-class12": check_class12}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list targets and exit")
    ap.add_argument("--run", action="append", default=[], choices=list(TARGETS),
                    help="target(s) to execute (repeatable)")
    ap.add_argument("--check", action="append", default=[], choices=list(CHECKS),
                    help="compare an existing output against the expected values, without running")
    ap.add_argument("--dataset-root", default="",
                    help="root of the separately distributed evaluation dataset "
                         "(appearance-class12)")
    ap.add_argument("--skip-train", action="store_true",
                    help="gait-class4: skip retraining, score existing checkpoints")
    a = ap.parse_args()

    if a.list or (not a.run and not a.check):
        print("Targets:")
        for k, (_, desc) in TARGETS.items():
            print(f"  {k:22s} {desc}")
        print("\nUsage: python reproduce/reproduce.py --run <target> [...]")
        return 0

    ok = True
    for t in a.check:
        ok &= CHECKS[t](a)
    for t in a.run:
        ok &= TARGETS[t][0](a)
    print(f"\nReport: {os.path.relpath(REPORT, os.getcwd())}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
